name: Containerise the project

on:
  push:
    branches: [main_FEAT_improve-ci-tags]
    tags:
      - 'v*'
  pull_request:
    branches: [main_FEAT_improve-ci-tags]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image (dev)
        id: build-dev
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name == 'push' && github.repository == 'aldbr/diracx-web' && github.ref_name == 'main' }}
          tags: |
            ghcr.io/aldbr/diracx-web/static:dev
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build Docker image
        id: build-tag
        if: ${{ github.repository == 'aldbr/diracx-web' && startsWith(github.ref, 'refs/tags/v') }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/aldbr/diracx-web/static:${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max