name: Deployment

on: [push, pull_request]

jobs:
  release-please:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.repository == 'aldbr/diracx-web' }}
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: ${{ github.ref_name }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      - name: Check if release was created
        env:
          RELEASE_CREATED: ${{ needs.release-please.outputs.release_created }}
          TAG_NAME: ${{ needs.release-please.outputs.tag_name }}
        run: |
          echo "Release created: ${RELEASE_CREATED}"
          echo "Tag name: ${TAG_NAME}"

  build-deploy-dev-image:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'push' || github.repository == 'aldbr/diracx-web' }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image (dev)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name == 'push' && github.repository == 'aldbr/diracx-web' && github.ref_name == 'main_FEAT_improve-ci-tags' }}
          tags: ghcr.io/aldbr/diracx-web/static:dev
          platforms: linux/amd64,linux/arm64

  build-deploy-release-image:
    runs-on: ubuntu-latest
    needs: release-please
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if release was created
        env:
          RELEASE_CREATED: ${{ needs.release-please.outputs.release_created }}
          TAG_NAME: ${{ needs.release-please.outputs.tag_name }}
        run: |
          echo "Release created: ${RELEASE_CREATED}"
          echo "Tag name: ${TAG_NAME}"

      - name: Build Docker image
        if: ${{ needs.release-please.outputs.release_created == 'true' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/aldbr/diracx-web/static:${{ needs.release-please.outputs.tag_name }}
          platforms: linux/amd64,linux/arm64