name: Release Please

on:
  push:
    branches:
      - main_FEAT_improve-ci-tags

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          target-branch: main_FEAT_improve-ci-tags
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json