name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
              
      - name: Trigger tests
        run: npm run test
